columns = [
    "todo",
    "in-progress",
    "review",
    "done",
]
done_column = "done"

[project]
name = "resumezen"
key = "ZG"

[tui]
confirm_quit = true

[tui.key_bindings]
add = ["a"]
cancel_quit = [
    "n",
    "N",
]
clear_filter = ["Esc"]
confirm_quit = [
    "y",
    "Y",
    "q",
    "Q",
    "Enter",
    "Esc",
]
dependency_add = ["d"]
dependency_remove = ["D"]
details = ["v"]
edit = ["e"]
help = ["?"]
maximize = ["m"]
move_left = [
    "H",
    "Shift+Left",
]
move_right = [
    "L",
    "Shift+Right",
]
parent = ["p"]
popup_close = [
    "v",
    "Esc",
    "q",
]
popup_scroll_down = [
    "j",
    "Down",
]
popup_scroll_up = [
    "k",
    "Up",
]
popup_select_down = [
    "J",
    "Shift+Down",
]
popup_select_left = [
    "H",
    "Shift+Left",
]
popup_select_right = [
    "L",
    "Shift+Right",
]
popup_select_up = [
    "K",
    "Shift+Up",
]
quit = [
    "q",
    "Esc",
]
regex_search = ["Ctrl+?"]
reload = ["r"]
reorder_down = [
    "J",
    "Shift+Down",
]
reorder_up = [
    "K",
    "Shift+Up",
]
search = ["/"]
select_down = [
    "j",
    "Down",
]
select_left = [
    "h",
    "Left",
]
select_right = [
    "l",
    "Right",
]
select_up = [
    "k",
    "Up",
]
shell = ["Q"]
toggle_expand = [
    "Space",
    "Enter",
]

[storage]
backend = "file"

[wip]
enabled = true

[display]
markdown = true
timezone = "local"

[points]
aggregate_children = false
